name: tennis-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xgboost
  - lightgbm
  - catboost
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - scikit-learn
  - scipy
  - pyarrow
  - pip
  - pip:
      - kaggle

